





services:
  backend:
    build: .
    container_name: sweetshop_backend_service
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:mysql://db:3306/sweetshop_db?createDatabaseIfNotExist=true
      - DB_USER=${DB_USER} # Reads from .env file
      - DB_PASS=${DB_PASS} # Reads from .env file
      - JWT_SECRET=${JWT_SECRET} # Reads from .env file
      - ADMIN_INVITE_CODE=${ADMIN_INVITE_CODE} # Reads from .env file
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: sweetshop_mysql_db
    ports:
      - "3307:3306"
    environment:
      # Use the same variable for consistency
      - MYSQL_ROOT_PASSWORD=${DB_PASS} 
      - MYSQL_DATABASE=sweetshop_db
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: