version: '3.8'

services:
  # Backend Application Service
  backend:
    build: .
    container_name: sweetshop_backend_service
    ports:
      - "8080:8080"
    environment:
      # Update the DB_URL to point to the 'db' service name instead of host.docker.internal
      - DB_URL=jdbc:mysql://db:3306/sweetshop_db?createDatabaseIfNotExist=true
      - DB_USER=root
      - DB_PASS=12345678
      - JWT_SECRET=8fKq9R4u7x!A%D*G-KaPdSgVkYp3s6v9
    depends_on:
      - db # Tells the backend to wait for the db service to start

  # MySQL Database Service
  db:
    image: mysql:8.0 # Use the official MySQL 8.0 image
    container_name: sweetshop_mysql_db
    ports:
      # Map your local machine's port 3307 to the container's port 3306
      # This avoids conflicts if you have another MySQL running on port 3306 locally
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=sweetshop_db
    volumes:
      - mysql-data:/var/lib/mysql # Persist database data on your host machine

volumes:
  mysql-data: # Defines the named volume